name: Revolution healthcare
favicon: null
layout_spectrum: 0.5178513550199568
typography_spectrum: 0.5173921424429864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.22476044832728803
  lightness: 0.9407954879570752
  saturation: 0.9472960811108351
  rhythmicContrast: 0.9258976127021015
purpose: []
